name: NASA APOD ETL

on:
  schedule:
    - cron: '0 6,14,22 * * *'  # Runs at 6:00 AM, 2:00 PM, and 10:00 PM UTC
  workflow_dispatch:

jobs:
  fetch-apod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python etl_apod.py

      - name: Check for changes
        id: check_changes
        run: |
          cd apod
          if [[ -n "$(git status --porcelain .)" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update APOD for $(date -u +'%Y-%m-%d %H:%M')"
          file_pattern: 'apod/**'
          commit_user_name: github-actions[bot]
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "Narayan Soni <soninarayan@users.noreply.github.com>"
          status_options: -A
